% generate_bindings.m

% include_dirs = "/usr/local/include";
include_dirs = "/home/warnes/matlab/bladeRF/include"
library_dirs = "/usr/lib/x86_64-linux-gnu/";
libraries = fullfile(library_dirs(1), "libbladeRF.so");

clibgen.generateLibraryDefinition( ...
    "/home/warnes/matlab/bladeRF/include/libbladeRF.h", ...
    IncludePath                      = include_dirs, ...
    Libraries                        = libraries, ...
    OverwriteExistingDefinitionFiles = true, ...
    DefinedMacros                    = "MATLAB_LINUX_THUNK_BUILD_", ...
    TreatConstCharPointerAsCString   = true, ...
    Verbose                          = true, ...
    AdditionalCompilerFlags          = "-L" + library_dirs, ... + " -std=c++14", ...
    AdditionalLinkerFlags            = "-L" + library_dirs, ...
    TreatObjectPointerAsScalar       = true, ...
    TreatConstCharPointerAsCString   = true, ...
    CLinkage                         = false ...
    );

